### ISSUE TITLE
batch_pubmed_download function returns a message "Killing the request! Something is not working. Please, try again later"

### ISSUE THREAD

**Issue by Alpashano** [dami82/easyPubMed#12]
I am trying to batch PMIDs for my query and receive this message:
> require(easyPubMed)
> search.string<-'"1992/05/01 00:00":"2021/09/28 06:00"[Date - Entry] AND "medline"[Filter]'
> ids <-get_pubmed_ids(search.string)
> PopulationSetUpdate<-batch_pubmed_download(ids, batch_size = 5000, format = "uilist")
Killing the request! Something is not working. Please, try again later
Killing the request! Something is not working. Please, try again later

**Comment by dami82** [comment]
You are passing the wrong input. Just have a look at the manual:
```?easyPubMed::batch_pubmed_download```
You should pass the query string (*i.e.,* `search.string`), not a list.

Also, see this note: <https://ncbiinsights.ncbi.nlm.nih.gov/2022/09/13/updated-pubmed-eutilities/>
At this moment (and until I push an update of `easyPubMed` that is tailored to the very recent updates of NCBI's *eutilities*, you won't be able to retrieve more than 10,000 records/PMIDs from a single query. Your query returned million of results, so it won't work. Sorry for the inconvenience. I hope I'll find time to rewrite my R package during the end-of-the-year break.
