### ISSUE TITLE
Problem with October pub dates

### ISSUE THREAD

**Issue by buyske** [dami82/easyPubMed#2]
The article_to_df function seems to convert at least some October publication dates to a value of month equal to 0. For example,

get_pubmed_ids(27463701) %>% fetch_pubmed_data() %>% article_to_df(getAuthors = FALSE)

shows the correct year, but the month is given as 0 instead of 10.

**Comment by dami82** [comment]
Hi Steve,

thanks for using easyPubMed and for the message. I could reproduce this
issue (thanks for attaching the example). I will work on this in the next
few days and keep you posted.
FYI, the *article_to_df()* output typically includes the date found in the
<DateCompleted> field (and NOT the <PubDate> field).
Therefore, the expected output should be: year:2017, month:06,  day:05
I'll keep you posted.


Il giorno dom 9 feb 2020 alle ore 17:59 Steve Buyske <
notifications@github.com> ha scritto:

**Comment by dami82** [comment]
article_to_df() was updated, and the bug was fixed. 
The following code now returns the expected result, i.e. "10".

get_pubmed_ids(27463701) %>% fetch_pubmed_data() %>% 
    article_to_df(getAuthors = FALSE) %>% pull(month)
