### ISSUE TITLE
Email regex fails for 2-character university domains (e.g., author@bu.edu, author@uw.edu)

### ISSUE THREAD

**Issue by jcetron** [dami82/easyPubMed#20]
Hi @dami82,

When retrieving author email addresses, emails for universities with two-letter abbreviations such as BU (Boston University) are not retrieved due to a limitation in the regex pattern. Here is the regex from the source ([line 255](https://github.com/dami82/easyPubMed/blame/master/R/easyPubMed_src.R#L255) of `easyPubMed_src.R`):

```
email.PAT <- "([[:alnum:]]|\\.|\\-|\\_){3,200}@([[:alnum:]]|\\.|\\-|\\_){3,200}(\\.)([[:alnum:]]){2,6}"
```

As written, the `{3,200}` criteria for the set of characters immediately following the `@` symbol restricts email address domains to a minimum of three characters. So for example, addresses like author@mit.edu are returned properly, but addresses like author@bu.edu are returned empty (`""`).

This seems easily fixed by modifying the regex to the following:

```
email.PAT <- "([[:alnum:]]|\\.|\\-|\\_){3,200}@([[:alnum:]]|\\.|\\-|\\_){2,200}(\\.)([[:alnum:]]){2,6}"
```

Is there any reason this fix can't or shouldn't be implemented? Was the pattern set to start at three-character domains for a specific reason that I'm not catching (e.g., some unexpected bug it can cause)?

If it's possible to change this to fix the issue, it would be great to have the edit implemented here. I am working with a team along with @Epi-Emma on a project where we are using `easyPubMed` to retrieve author emails, and the team specifically includes additional collaborators at BU, so it would be a real problem to exclude those addresses due to this bug. (I'll note as well that we are already using the development version of the package, since you have repaired the regex here to fix the issue of underscore characters not being escaped correctly in the CRAN version.)

Thank you so much!
Josh

**Comment by dami82** [comment]
Thanks for the feedback. Implemented.
