### ISSUE TITLE
Differences with number of records in Pubmed website

### ISSUE THREAD

**Issue by FedeGiovannetti** [dami82/easyPubMed#23]
Hello! Thanks for this useful package. It made my workflow much more easy.

I'm using EasyPubMed for querying the following terms: "((SES) OR (poverty)) AND (brain)" and it returns a total of 2237 records. However, when I enter the same query in Pubmed's site, it retrieves 2242 records. 

One posibility that I infer is that EasyPubmed is not counting the "books and documents" tag while PubMed does. My infer is based in the fact that in this query there are only 5 "books and documents", which is the exact amount of missing records. Is this the reason of the difference? Is it another? Is there a way of obtaining the same number of records?

Thanks!

**Comment by dami82** [comment]
Dear Federico,

Thanks for the message and for using `easyPubMed`.
Great catch. You are correct!
I updated the library. The latest version of `easyPubMed` (3.1.3) supports
downloading "Books and Document" records in `xml` format. I ran a few tests
and everything seems to be working properly. However, if you run into any
issues, please let me know. Also, please note that the `epm_parse()`
function will just skip "Books and Document" entries (non-compatible
structure of xml tags compared to PubMed articles).
Thanks.

Best regards,
Damiano

**Comment by FedeGiovannetti** [comment]
Thanks Damiano! Everything works fine now. I'm using EasyPubMed for a specific [shinyapp ](http://fedegiovannetti.shinyapps.io/sesneurosciencerefs) so maybe I'll come back with further questions and comments in the near future.
